### ISSUE TITLE
PHP 8 support?

### ISSUE THREAD

**Issue by hurrtz** [cytopia/sweany#1]
Dear Mr Cytopia,

I am thinking about creating a new project of the likes of "Facebook meets Alibaba meets Gmail", basically the emacs of web pages, and I now need to decide upon a proper PHP framework my project can be rooted on. I have heard some good things about Sweany so I wanted to know if you happen to have plans in adopting the upcoming PHP 8?

Sincerely
hurrtz

**Comment by cytopia** [comment]
I see what you mean

![Screenshot 2020-07-11 13-49-47  selection](https://user-images.githubusercontent.com/12533999/87223462-6faa9500-c37d-11ea-933e-bf9cc12227d1.png)

**Comment by cytopia** [comment]
Dear @hurrtz 

I've added full PHP 8 support. Can you check if this is working for you.

PR: https://github.com/cytopia/sweany/pull/2

**Comment by hurrtz** [comment]
Dear @cytopia 

This does indeed look perfectly fine. Sweany is now a serious canditate for my next project, and if I happen to actually use Sweany I will make sure to drop you a line.

Thank you for all your effort on such a short notice
hurrtz
